language: python
install:
  - pip install rstcheck
  - pip install bashate
script:
  - rstcheck README.rst
  - bashate reload
  - bashate fog_setup
  - bashate fog_min_setup.sh
  - bashate fog_full_setup.sh

